<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-01T15:53:25Z" name="Suite" finished-at="2024-02-01T15:54:23Z" duration-ms="57612">
    <groups>
      <group name="purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" name="submitOrder" class="vjacademy.tests.SubmitOrderTest"/>
      </group> <!-- purchase -->
      <group name="ErrorTests">
        <method signature="ErrorValidationTests.LoginErrorValidation()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" name="LoginErrorValidation" class="vjacademy.tests.ErrorValidationTests"/>
      </group> <!-- ErrorTests -->
    </groups>
    <test started-at="2024-02-01T15:53:25Z" name="Submit Order Test" finished-at="2024-02-01T15:53:53Z" duration-ms="27943">
      <class name="vjacademy.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:25Z" name="launchApp" finished-at="2024-02-01T21:23:33Z" duration-ms="7827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:33Z" name="submitOrder" data-provider="getdata" finished-at="2024-02-01T21:23:41Z" duration-ms="8273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pname=IPHONE, pwd=Hunt4@job, email=vjcrypto1010@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:41Z" name="teardown" finished-at="2024-02-01T21:23:42Z" duration-ms="436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:42Z" name="launchApp" finished-at="2024-02-01T21:23:44Z" duration-ms="2731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:44Z" name="submitOrder" data-provider="getdata" finished-at="2024-02-01T21:23:52Z" duration-ms="8213" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pname=ZARA, pwd=Hunt4@job, email=vijay@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:52Z" name="teardown" finished-at="2024-02-01T21:23:53Z" duration-ms="410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method signature="orderHistoryTest(java.lang.String)[pri:0, instance:vjacademy.tests.SubmitOrderTest@68c72235]" started-at="2024-02-01T21:23:53Z" name="orderHistoryTest" finished-at="2024-02-01T21:23:53Z" depends-on-methods="vjacademy.tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method orderHistoryTest requires 1 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method orderHistoryTest requires 1 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:191)
	at org.testng.internal.Parameters.createParameters(Parameters.java:127)
	at org.testng.internal.Parameters.createParameters(Parameters.java:376)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
      </class> <!-- vjacademy.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2024-02-01T15:53:54Z" name="Error Validation Tests" finished-at="2024-02-01T15:54:23Z" duration-ms="29029">
      <class name="vjacademy.tests.ErrorValidationTests">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:23:54Z" name="launchApp" finished-at="2024-02-01T21:24:02Z" duration-ms="8150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:24:02Z" name="LoginErrorValidation" finished-at="2024-02-01T21:24:03Z" duration-ms="912" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect emafil or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect emafil or password.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at vjacademy.tests.ErrorValidationTests.LoginErrorValidation(ErrorValidationTests.java:25)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:24:05Z" name="teardown" finished-at="2024-02-01T21:24:06Z" duration-ms="540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:24:06Z" name="launchApp" finished-at="2024-02-01T21:24:12Z" duration-ms="6845" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:24:12Z" name="ProductErrorValidation" finished-at="2024-02-01T21:24:22Z" duration-ms="9784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:vjacademy.tests.ErrorValidationTests@cad498c]" started-at="2024-02-01T21:24:22Z" name="teardown" finished-at="2024-02-01T21:24:23Z" duration-ms="428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- vjacademy.tests.ErrorValidationTests -->
    </test> <!-- Error Validation Tests -->
  </suite> <!-- Suite -->
</testng-results>
